#!/usr/bin/env perl

package grabhalo;

use strict;
use warnings;

use Mojolicious::Lite;
use DBI;
use Digest::SHA qw(sha256);

app->sessions->default_expiration(86400);
app->secret('MySecretKey');

my $dbh = DBI->connect("dbi:SQLite:database.db","","") or die "Could not connect";

# shortcut for use in template
helper db => sub { $dbh }; 

my $insert;
my $createDummyAccounts = 0;
while (1) {
  # create insert statement
  $insert = eval { $dbh->prepare('INSERT INTO users VALUES (?,?,?,?)') } || die $!;
  # break out of loop if statement prepared
#  last if $insert;

  # if statement didn't prepare, assume its because the table doesn't exist
  warn "Creating table 'people'\n";
  $createDummyAccounts = 1;
  $dbh->do('CREATE TABLE users(
id INT PRIMARY KEY, 
username VARCHAR(30), 
password VARCHAR(256), 
loggedin BOOLEAN);');
  $dbh->do('CREATE TABLE sentMessages(
senderId VARCHAR(30), 
receiverId VARCHAR(30), 
subject TEXT,
message TEXT VARCHAR(256), 
date DATE, 
time TIME,
FOREIGN KEY(senderId) REFERENCES users(id),
FOREIGN KEY(receiverId) REFERENCES users(id));');
  $dbh->do('CREATE TABLE inbox(
ownerId VARCHAR(30), 
receiverId VARCHAR(30), 
subject TEXT,
message TEXT, 
date DATE, 
time TIME,
read BOOLEAN,
FOREIGN KEY(ownerId) REFERENCES users(id),
FOREIGN KEY(receiverId) REFERENCES users(id));');
}

my $username="username";
if( $createDummyAccounts )
{
    for( my $id = 0; $id < 10; $id++ )
    {
	$insert->execute($id, $username.$id, sha256($username.$id), "false");
    }
}

any '/' => sub
{
    my $self = shift;
    $self->stash(error => "");
    if( !isLoggedIn($self) )
    {
 	$self->redirect_to('/loginPage');
    }
};

any '/login' => sub {
    my $self = shift;
    if( !isLoggedIn($self) )
    {
	my $username = $self->param('username');
	my $password = $self->param('password');
	my $id;
#	checkUserPass($self, $username, $password, \$id);
	if( checkUserPass($self, $username, $password) )
	{
	    $self->session(username => $username);
	    $self->session(loggedIn => "true");
	    $self->redirect_to('account');
	}
	else
	{
	    $self->flash(error => 'Invalid username/password');
	    $self->redirect_to('/loginPage');
	}
    }
};

any '/loginPage' => 'login/index';

any '/account' => sub {
    my $self = shift;
    if( !isLoggedIn($self) )
    {
	$self->redirect_to('/loginPage');
    }
};

any '/sendMessages' => sub {
    my $self = shift;
    if( (defined $self->session('loggedIn')) && ($self->session('loggedIn') eq 'true'))
    {
	my $username = $self->session('username');
	if( getAllUsers($self, $username) )
	{
	    $self->render('sendMessages/index');
	}
    }
    else
    {
	$self->render('/loginPage');
    }
};

any '/sendSelMessages' => sub {
    my $self = shift;
    my $subject = $self->param('subject');
    my $message = $self->param('message');
    my $insert1 = eval { $self->$dbh->prepare('INSERT INTO inbox VALUES (?,?,?,?,?,?)') } || die $!;
    my $insert2 = eval { $self->$dbh->prepare('INSERT INTO sentMessages VALUES (?,?,?,?,?,?)') } || die $!;
    
    my $i = 0;
    foreach( $self->param )
    {
	if( $self->param($_) =~ /^\d+$/ )
	{
	    $insert->execute($self->session(id), $self->param($_), $subject, $message 
	}
	$self->session("text".$i => ($self->param($_)));
	$i++;
    }
    
    $self->redirect_to('/testSendSel');
};

any '/testSendSel' => sub {
    my $self = shift;
    $self->render('testSendSel/index');
};

any '/logout' => sub {
    my $self = shift;
    $self->session(loggedIn => 'false');
    $self->redirect_to('/loginPage');
};

any '/testdb' => sub {
    my $self = shift;
    $self->render('testdb/index');
};

sub getAllUsers()
{
    my ($self, $username) = @_;
    my $sth = eval { $dbh->prepare("SELECT id, username FROM users WHERE username!=\"$username\"") } || die $!;
    $sth->execute;
    my $array = $sth->fetchall_arrayref;
    $self->stash(otherUsers => $array);
    return 1;
}

sub isLoggedIn()
{
    my $self = $_[0];
    if( (defined $self->session('loggedIn')) && ($self->session('loggedIn') eq 'true'))
    {
#	$self->redirect_to('account');
	$self->render('account/index');
	return 1;
    }
    else
    {
	return 0;
    }
}

sub checkUserPass()
{
    my ($self, $username, $password, $id) = @_;
    $password = sha256 $password;
    my $sth = eval { $dbh->prepare("SELECT id, password FROM users WHERE username=\"$username\"") } || die $!;
    $sth->execute;
    my @row = $sth->fetchrow_array;
    # my $i = 0;
    # foreach my $val (@rows) 
    # {
    # 	$self->session("value".$i => $val);
    # 	$i++;
    # }

    # $self->session(foo => 'bar');
    # $self->session(pass => $password );

    # if( $password eq $self->session('value1') )
    # {
    # 	$self->session(equal => "true");
    # }
    # else
    # {
    # 	$self->session(equal => "false");	
    # }

    $id = $row[0];
    my $retrievedPass = $row[1];
    # $self->session(id => $id);
    # $self->session(pass => $retrievedPass);
    if( ($id ne "") && ($retrievedPass ne "") && ($retrievedPass eq $password) )
    {
	$self->session(id => $id);
	$self->session(username => $username);
	return 1;
#	$self->session(if1 => "true");	
    }
#     if( $retrievedPass ne "" )
#     {
# 	$self->session(if2 => "true");		
#     }
#     if($retrievedPass eq $password) 
#     {
# 	$self->session(id => $id);
# 	# $self->s(password => $retrievedPass);
# #	$self->redirect_to('/testdb');
# 	return 1;
#     }
    else
    {
	return 0;
    }
#    $self->redirect_to('/testdb');
};

app->start;

__DATA__

@@ testSendSel/index.html.ep
<html>
<body>
<%= session 'text1' %>
</body>
</html>

@@ testdb/index.html.ep
<html>
<body>
id
<%= session 'if1' %>
<br/>
<%= session 'if2' %>
<br/>
pass
<%= session 'id' %>
<br/>
<%= session 'pass' %>
<br/>
<%= session 'equal' %>
</body>
</html>

@@ login/index.html.ep
<!doctype html>
<html>
    <head>
    <script type="text/javascript" src="validateScript.js">
    </script>
    <title>
    Login page
    </title>
    </head>
    <body>
    <form name="login" method="post" onsubmit="return validateForm()" action="<%=url_for('login')->to_abs%>">
    <table>
    <tr>
    <td>
    Username
    </td>
    <td>
    <input type="text" name="username" maxlength="30"/>
    </td>
    <td id="usernameErr" style="text-color:red;">
    </td>
    </tr>
    <tr>
    <td>
    Password
    </td>
    <td>
    <input type="password" name="password" maxlength="30"/>
    </td>
    <td id="passErr" style="text-color:red;">
    </td>
    </tr>
    <tr>
    <td>
    <input type="submit" value="Login" />    
    </td>
    <td>
    <input type="reset" value="Reset" />
    </td>
    </tr>
    </table>
    </form>
    <br/>
    <label id="flashError" style="text-color:red">
    <%= flash 'error' %> 
    </label>
    </body>
</html>

@@ sendMessages/index.html.ep
<html>
<head>
<title>
Send Messages@
<%= session 'username' %>
</title>
<script type="text/javascript" src="validateScript.js" >
</script>
</head>
<body>
<%= include 'header/index' %>
<form name="sendMessage" method="post" action="<%=url_for('sendSelMessages')->to_abs%>" onsubmit="return validateSendMsg()">
<div style="float:left;">
Subject :
<br/>
<input type="text" name="subject" style="width:50%" />
<br/>
<br/>
<label id="msgErr">
Message Text :
</label>
<br/>
<textarea name="message" rows="20" cols="100">
</textarea>
<br/>
<input type="submit" value="Send" />
</div>
<table style="float:right;">
<th>
<td colspan="2" >
<b style="text-align:left;align:left;">
All users
</b>
</td>
</th>
<%= my $i; %>
% foreach my $row(@{$otherUsers}) { 
    <tr>
    % foreach my $text (@{$row}) { 
    % if( ($text =~ /^\d+$/) ) { 
    <td><input type="checkbox" name="selected" value="<%= $text %>"/></td>
    % } else {
    <td><%= $text %></td>
    % }
    % }
    </tr>
    % }
</table>
</form>
</body>
</html>
    
@@ account/index.html.ep
<!doctype html>
<html>
    <head>
    <title>
    <%= session 'username' %>
    </title>
    </head>
    <body>
    <%= include 'header/index' %>
    </body>
</html>

@@ header/index.html.ep
    <nav style="float:right;" >    
    <%= link_to "Send Messages" => 'sendMessages' %>
    &nbsp; | &nbsp;
    <%= link_to "Inbox" => 'inbox' %>
    &nbsp; | &nbsp;
    <%= link_to "Sent Messages" => 'sentMessages' %>
    &nbsp; | &nbsp;
    <%= link_to "Account Settings" => 'sendMessages' %>
    &nbsp; | &nbsp;
    <%= link_to Logout => 'logout' %>
    </nav>
    <br/>
    <hr/>

@@ validateScript.js    

function validateForm()
{
  alert("validateForm.");
  var username = document.forms["login"]["username"].value;
  var password = document.forms["login"]["password"].value;
  var blank = true;
  var userErr = document.getElementById('usernameErr');
  var passErr = document.getElementById('passErr');
  var flashErr = document.getElementById('flashError');
  flashErr.innerHTML = "";
  
  if( username == null || username == "")
  {
      alert("username = " + username);
      userErr.innerHTML = "Please enter the username";
      blank = false;
  }
  else
  {
      userErr.innerHTML = "";      
  }

  if( password == null || password == "")
  {
      alert("password = " + password);
      passErr.innerHTML = "Please enter the password";
      blank = false;
  }
  else
  {
      passErr.innerHTML = "";      
  }

  return blank;
}

function validateSendMsg()
{
    var form = document.forms["sendMessage"];
    var message = document.forms["sendMessage"]["message"].value;
    var all = document.forms["sendMessage"].elements;
    var size = all.length;
    var selected = false;
    var msgErr = document.getElementById('msgErr');
    
    for(var i = 0; i < form.selected.length; i++) 
    {
	if (form.selected[i].checked) 
	{
	    selected = true;
	    break;
	}
    }
    
    if( !selected )
    {
	msgErr.innerHTML = "Message Text :<br/>No recepients selected";
	return false;
    }
    else
    {
	msgErr.innerHTML = "Message Text :";
    }

    var re = "/\s+/gm";
    var newstr = message.replace(re, "");
    if( newstr == "" || newstr == null )
    {
	msgErr.innerHTML = "Message Text :<br/>Please enter text for your message"    
	    return false;
    }
    else
    {
	msgErr.innerHTML = "Message Text :";
	return true;
    }
}

function isAnInt(element) 
{
    return (parseInt(element) === element);
}

function sh(form) 
{
    for (var i = 0; i < form.sizes.length; i++) 
    {
	if (form.sizes[i].checked) {
	    break;
	}
    }
    alert(form.sizes[i].value);
} 
